Repository ros2/rmw_connext, pull requests merged in 2018-11, with the labels that each got.

#306 use new error handling API from rcutils
  rmw_connext_cpp/src/process_topic_and_service_names.cpp
  rmw_connext_dynamic_cpp/src/functions.cpp
  rmw_connext_shared_cpp/src/node_names.cpp
  rmw_connext_shared_cpp/src/service_names_and_types.cpp
  rmw_connext_shared_cpp/src/topic_names_and_types.cpp
  rmw_connext_shared_cpp/src/types/custom_data_reader_listener.cpp
Labels: enhancement, in review

#307 rename dynamic array to sequence
  rmw_connext_dynamic_cpp/src/functions.cpp
  rmw_connext_dynamic_cpp/src/macros.hpp
  rmw_connext_dynamic_cpp/src/templates.hpp
Labels: in review

#309 use uint8_t array
  rmw_connext_cpp/src/rmw_publish.cpp
  rmw_connext_cpp/src/rmw_serialize.cpp
  rmw_connext_cpp/src/rmw_take.cpp
Labels: in progress

#311 reduce verbosity when Connext is not available
  rmw_connext_cpp/CMakeLists.txt
  rmw_connext_dynamic_cpp/CMakeLists.txt
  rmw_connext_shared_cpp/CMakeLists.txt
Labels: enhancement, in review

#310 Add implementation of matching publisher/subscriber counts
  rmw_connext_cpp/include/rmw_connext_cpp/connext_static_publisher_info.hpp
  rmw_connext_cpp/include/rmw_connext_cpp/connext_static_subscriber_info.hpp
  rmw_connext_cpp/src/rmw_publisher.cpp
  rmw_connext_cpp/src/rmw_subscription.cpp
Labels: in progress

#308 refactor to support init options and context
  rmw_connext_cpp/src/rmw_guard_condition.cpp
  rmw_connext_cpp/src/rmw_init.cpp
  rmw_connext_cpp/src/rmw_node.cpp
  rmw_connext_dynamic_cpp/src/functions.cpp
Labels: enhancement, in review
