Repository ros2/rmw_connext, pull requests merged in 2018-06, with the labels that each got.

#285 Remove topic partitions
  rmw_connext_cpp/src/process_topic_and_service_names.cpp
  rmw_connext_cpp/src/process_topic_and_service_names.hpp
  rmw_connext_cpp/src/rmw_client.cpp
  rmw_connext_cpp/src/rmw_publisher.cpp
  rmw_connext_cpp/src/rmw_service.cpp
  rmw_connext_cpp/src/rmw_service_server_is_available.cpp
  rmw_connext_cpp/src/rmw_subscription.cpp
  rmw_connext_shared_cpp/src/node.cpp
  rmw_connext_shared_cpp/src/types/custom_publisher_listener.cpp
  rmw_connext_shared_cpp/src/types/custom_subscriber_listener.cpp
  rosidl_typesupport_connext_c/resource/srv__type_support_c.cpp.em
  rosidl_typesupport_connext_cpp/include/rosidl_typesupport_connext_cpp/service_type_support.h
  rosidl_typesupport_connext_cpp/resource/srv__rosidl_typesupport_connext_cpp.hpp.em
  rosidl_typesupport_connext_cpp/resource/srv__type_support.cpp.em
Labels: in review

#289 use size_t
  rmw_connext_cpp/src/rmw_take.cpp
  rosidl_typesupport_connext_c/resource/msg__type_support_c.cpp.em
  rosidl_typesupport_connext_cpp/include/rosidl_typesupport_connext_cpp/connext_static_cdr_stream.hpp
  rosidl_typesupport_connext_cpp/resource/msg__type_support.cpp.em
Labels: in progress

#259 Expose raw CDR stream for publish and subscribe
  rmw_connext_cpp/CMakeLists.txt
  rmw_connext_cpp/bin/apply-patch.py
  rmw_connext_cpp/resources/connext_static_serialized_data.idl
  rmw_connext_cpp/resources/patch_files/connext_static_serialized_data.cxx.patch
  rmw_connext_cpp/resources/patch_files/connext_static_serialized_data.h.patch
  rmw_connext_cpp/resources/patch_files/connext_static_serialized_dataPlugin.cxx.patch
  rmw_connext_cpp/resources/patch_files/connext_static_serialized_dataPlugin.h.patch
  rmw_connext_cpp/resources/patch_files/connext_static_serialized_dataSupport.cxx.patch
  rmw_connext_cpp/resources/patch_files/connext_static_serialized_dataSupport.h.patch
  rmw_connext_cpp/src/rmw_client.cpp
  rmw_connext_cpp/src/rmw_publish.cpp
  rmw_connext_cpp/src/rmw_publisher.cpp
  rmw_connext_cpp/src/rmw_serialize.cpp
  rmw_connext_cpp/src/rmw_service.cpp
  rmw_connext_cpp/src/rmw_subscription.cpp
  rmw_connext_cpp/src/rmw_take.cpp
  rmw_connext_cpp/src/type_support_common.hpp
  rosidl_typesupport_connext_c/CMakeLists.txt
  rosidl_typesupport_connext_c/resource/msg__type_support_c.cpp.em
  rosidl_typesupport_connext_cpp/RawData.idl
  rosidl_typesupport_connext_cpp/include/rosidl_typesupport_connext_cpp/connext_static_cdr_stream.hpp
  rosidl_typesupport_connext_cpp/include/rosidl_typesupport_connext_cpp/message_type_support.h
  rosidl_typesupport_connext_cpp/resource/msg__rosidl_typesupport_connext_cpp.hpp.em
  rosidl_typesupport_connext_cpp/resource/msg__type_support.cpp.em
Labels: in progress

#274 Only set NDDSHOME if not previously set
  connext_cmake_module/CMakeLists.txt
  connext_cmake_module/env_hook/connext.bat.in
  connext_cmake_module/env_hook/connext.sh.in
Labels: in review

#290 update usage of rcutils_join_path()
  rmw_connext_shared_cpp/src/node.cpp
Labels: in review

#291 export / use typesupport libraries separately
  rosidl_typesupport_connext_c/cmake/rosidl_typesupport_connext_c_generate_interfaces.cmake
  rosidl_typesupport_connext_cpp/cmake/rosidl_typesupport_connext_cpp_generate_interfaces.cmake
Labels: enhancement, in review

#292 add serialized functions
  rmw_connext_dynamic_cpp/src/functions.cpp
Labels: in progress

#293 Connext env hook: Extra fix for paths with spaces in them
  connext_cmake_module/env_hook/connext.bat.in
Labels: in review

#294 Use key rti-connext-dds as package key name for connext.
  rmw_connext_cpp/package.xml
  rmw_connext_dynamic_cpp/package.xml
  rmw_connext_shared_cpp/package.xml
  rosidl_typesupport_connext_cpp/package.xml
Labels: in review

#295 Split typesupport and cmake module packages into another repository.
  connext_cmake_module/CMakeLists.txt
  connext_cmake_module/cmake/Modules/FindConnext.cmake
  connext_cmake_module/cmake/check_abi.cmake
  connext_cmake_module/cmake/check_abi.cpp
  connext_cmake_module/connext_cmake_module-extras.cmake
  connext_cmake_module/env_hook/connext.bat.in
  connext_cmake_module/env_hook/connext.sh.in
  connext_cmake_module/package.xml
  rosidl_typesupport_connext_c/CMakeLists.txt
  rosidl_typesupport_connext_c/bin/rosidl_typesupport_connext_c
  rosidl_typesupport_connext_c/cmake/rosidl_typesupport_connext_c_generate_interfaces.cmake
  rosidl_typesupport_connext_c/include/rosidl_typesupport_connext_c/identifier.h
  rosidl_typesupport_connext_c/include/rosidl_typesupport_connext_c/visibility_control.h
  rosidl_typesupport_connext_c/package.xml
  rosidl_typesupport_connext_c/resource/msg__rosidl_typesupport_connext_c.h.em
  rosidl_typesupport_connext_c/resource/msg__type_support_c.cpp.em
  rosidl_typesupport_connext_c/resource/rosidl_typesupport_connext_c__visibility_control.h.in
  rosidl_typesupport_connext_c/resource/srv__rosidl_typesupport_connext_c.h.em
  rosidl_typesupport_connext_c/resource/srv__type_support_c.cpp.em
  rosidl_typesupport_connext_c/rosidl_typesupport_connext_c-extras.cmake.in
  rosidl_typesupport_connext_c/rosidl_typesupport_connext_c/__init__.py
  rosidl_typesupport_connext_c/src/identifier.cpp
  rosidl_typesupport_connext_cpp/CMakeLists.txt
  rosidl_typesupport_connext_cpp/RawData.idl
  rosidl_typesupport_connext_cpp/bin/rosidl_typesupport_connext_cpp
  rosidl_typesupport_connext_cpp/cmake/rosidl_typesupport_connext_cpp_generate_interfaces.cmake
  rosidl_typesupport_connext_cpp/include/rosidl_typesupport_connext_cpp/connext_static_cdr_stream.hpp
  rosidl_typesupport_connext_cpp/include/rosidl_typesupport_connext_cpp/identifier.hpp
  rosidl_typesupport_connext_cpp/include/rosidl_typesupport_connext_cpp/message_type_support.h
  rosidl_typesupport_connext_cpp/include/rosidl_typesupport_connext_cpp/message_type_support_decl.hpp
  rosidl_typesupport_connext_cpp/include/rosidl_typesupport_connext_cpp/service_type_support.h
  rosidl_typesupport_connext_cpp/include/rosidl_typesupport_connext_cpp/service_type_support_decl.hpp
  rosidl_typesupport_connext_cpp/include/rosidl_typesupport_connext_cpp/visibility_control.h
  rosidl_typesupport_connext_cpp/package.xml
  rosidl_typesupport_connext_cpp/resource/msg__rosidl_typesupport_connext_cpp.hpp.em
  rosidl_typesupport_connext_cpp/resource/msg__type_support.cpp.em
  rosidl_typesupport_connext_cpp/resource/rosidl_typesupport_connext_cpp__visibility_control.h.in
  rosidl_typesupport_connext_cpp/resource/srv__rosidl_typesupport_connext_cpp.hpp.em
  rosidl_typesupport_connext_cpp/resource/srv__type_support.cpp.em
  rosidl_typesupport_connext_cpp/rosidl_typesupport_connext_cpp-extras.cmake.in
  rosidl_typesupport_connext_cpp/rosidl_typesupport_connext_cpp/__init__.py
  rosidl_typesupport_connext_cpp/src/identifier.cpp
Labels: in progress

#296 Prepare 0.5.0
  rmw_connext_cpp/package.xml
  rmw_connext_dynamic_cpp/package.xml
  rmw_connext_shared_cpp/package.xml
Labels: in review
