Repository ros2/rmw_connext, pull requests merged in 2019-10, with the labels that each got.

#368 update signature for added pub/sub options
  rmw_connext_cpp/include/rmw_connext_cpp/connext_static_subscriber_info.hpp
  rmw_connext_cpp/src/rmw_publisher.cpp
  rmw_connext_cpp/src/rmw_subscription.cpp
Labels: enhancement

#369 Fix build error introduced in #368
  rmw_connext_cpp/src/rmw_take.cpp
Labels: bug, in review

#370 suppress invalid syntax warning for macro call
  rmw_connext_cpp/src/rmw_client.cpp
  rmw_connext_cpp/src/rmw_publisher.cpp
  rmw_connext_cpp/src/rmw_service.cpp
  rmw_connext_cpp/src/rmw_subscription.cpp
Labels: in review

#374 update logic / patches to optionally support Connext 6
  rmw_connext_cpp/CMakeLists.txt
  rmw_connext_cpp/resources/patch_files_v6/connext_static_serialized_data.cxx.patch
  rmw_connext_cpp/resources/patch_files_v6/connext_static_serialized_data.h.patch
  rmw_connext_cpp/resources/patch_files_v6/connext_static_serialized_dataPlugin.cxx.patch
  rmw_connext_cpp/resources/patch_files_v6/connext_static_serialized_dataPlugin.h.patch
  rmw_connext_cpp/resources/patch_files_v6/connext_static_serialized_dataSupport.cxx.patch
  rmw_connext_cpp/resources/patch_files_v6/connext_static_serialized_dataSupport.h.patch
  rmw_connext_shared_cpp/include/rmw_connext_shared_cpp/ndds_include.hpp
Labels: enhancement, in review

#367 Zero copy api
  rmw_connext_cpp/src/rmw_publish.cpp
  rmw_connext_cpp/src/rmw_publisher.cpp
  rmw_connext_cpp/src/rmw_subscription.cpp
  rmw_connext_cpp/src/rmw_take.cpp
  rmw_connext_dynamic_cpp/src/functions.cpp
Labels: enhancement

#373 Support localhost only communication
  rmw_connext_cpp/src/rmw_node.cpp
  rmw_connext_dynamic_cpp/src/functions.cpp
  rmw_connext_shared_cpp/include/rmw_connext_shared_cpp/node.hpp
  rmw_connext_shared_cpp/src/node.cpp
Labels: enhancement
