Repository ros2/rmw_connext, pull requests merged in 2019-05, with the labels that each got.

#353 Stub out new allocation APIs.
  rmw_connext_cpp/src/rmw_publish.cpp
  rmw_connext_cpp/src/rmw_publisher.cpp
  rmw_connext_cpp/src/rmw_subscription.cpp
  rmw_connext_cpp/src/rmw_take.cpp
Labels: in progress

#354 Combine package name with type namespace in type support struct
  rmw_connext_cpp/src/rmw_publisher.cpp
  rmw_connext_cpp/src/rmw_subscription.cpp
  rmw_connext_cpp/src/type_support_common.hpp
  rmw_connext_dynamic_cpp/src/functions.cpp
  rmw_connext_dynamic_cpp/src/utility_templates.hpp
  rmw_connext_shared_cpp/src/demangle.cpp
Labels: in review

#355 Add missing get_serialized_message_size method.
  rmw_connext_cpp/src/rmw_serialize.cpp
Labels: bug, in progress
