Repository ros2/rmw_connext, pull requests merged in 2020-04, with the labels that each got.

#392 API changes to sync with one Participant per Context change in rmw_fastrtps
  rmw_connext_cpp/src/rmw_init.cpp
  rmw_connext_cpp/src/rmw_node.cpp
  rmw_connext_cpp/src/rmw_node_names.cpp
  rmw_connext_dynamic_cpp/src/functions.cpp
  rmw_connext_shared_cpp/include/rmw_connext_shared_cpp/node.hpp
  rmw_connext_shared_cpp/include/rmw_connext_shared_cpp/node_names.hpp
  rmw_connext_shared_cpp/src/node.cpp
  rmw_connext_shared_cpp/src/node_names.cpp
Labels: in review

#406 Do not force 510 locators compatibility mode
  rmw_connext_shared_cpp/src/node.cpp
Labels: in review

#399 Replace rosidl_generator_x for rosidl_runtime_x
  rmw_connext_cpp/CMakeLists.txt
  rmw_connext_cpp/package.xml
  rmw_connext_dynamic_cpp/CMakeLists.txt
  rmw_connext_dynamic_cpp/package.xml
Labels: enhancement

#414 More verbose error output when apply_patch.py fails
  rmw_connext_cpp/bin/apply-patch.py
Labels: in review

#417 set connext buffer capacity
  rmw_connext_cpp/src/rmw_take.cpp
Labels: bug
