Repository ros2/rmw_connext, pull requests merged in 2020-09, with the labels that each got.

#458 Fix wrong error messages
  rmw_connext_cpp/src/rmw_publisher.cpp
  rmw_connext_cpp/src/rmw_subscription.cpp
Labels: bug

#463 Updated rmw_* return codes
  rmw_connext_cpp/src/rmw_publisher.cpp
  rmw_connext_cpp/src/rmw_subscription.cpp
  rmw_connext_shared_cpp/include/rmw_connext_shared_cpp/wait.hpp
  rmw_connext_shared_cpp/src/wait_set.cpp
Labels: enhancement

#466 returned RMW_RET_INCORRECT_RMW_IMPLEMENTATION in rmw_service_server_is_available
  rmw_connext_cpp/src/rmw_service_server_is_available.cpp
  rmw_connext_dynamic_cpp/src/functions.cpp
Labels: enhancement

#467 Return RMW_RET_UNSUPPORTED in rmw_get_serialized_message_size
  rmw_connext_cpp/src/rmw_serialize.cpp
Labels: tests
